### ISSUE TITLE
Port add and remove

### ISSUE THREAD

**Issue by giumc** [amccaugh/phidl#104]
I noticed that in a situation like this:

```
import phidl.geometry as pg
import phidl.device_layout as dl

c=dl.Device(name='test')

p=dl.Port()

c.add_port(p)

print(c)

c.remove(p)

print(c)
```
the Device ```c ``` doesn't lose ```p``` when it is asked to remove it. 
By looking at your code, it seems that the ```Device.remove``` method tries to compare ```p``` with existing ports, but fails to recognize the identity. I implemented a magic method ```__eq__``` for the Port, but I am not sure It will be a good implementation ( I believe I opened a "pull request" but not sure I am doing the right thing , let me know if this is any good )

GM

**Comment by amccaugh** [comment]
Hi @giumc , the issue here is that when you pass `add_port()` an existing port, it *copies* it.  This is to make it easy to copy ports from one object to another (for instance, from an underlying reference into the parent device).  So really what you have here is:

```
c=dl.Device(name='test')
first_port = dl.Port()
copy_of_first_port = c.add_port(first_port)
c.remove(copy_of_first_port) # This fails because c contains first_port only
```

On a sidenote, PHIDL is written in a way that encourages you to use `add_port` to simultaneously create the port & add it to a Device, rather than the gdspy way of creating objects, then adding them in a separate step.  So generally, rather than doing

```
p=dl.Port(name = 'myport')
c.add_port(p)
```

it's more convenient to do
```
p = c.add_port(name = 'myport')
```

It's done this way because amount of times we've observed people actually wanting to reuse polygons, ports, etc is vanishingly small -- so we chose not to separate the creation from the addition
