### ISSUE TITLE
quickplots not showing

### ISSUE THREAD

**Issue by cloudcalvin** [amccaugh/phidl#110]
Hi there.

I am having the issue where my plots aren't showing and I think it might be the same issue as described here https://github.com/amccaugh/phidl/issues/91, 

but in the examples/tutorial you don't use `set_quickplot_options(blocking=True)` so I am wondering why it is not an issue for you. 

Any thoughts?

**Comment by amccaugh** [comment]
Hi @cloudcalvin , I think a pretty common use-case (that I also follow) is that people use a REPL to do programming in PHIDL, such as ipython or vscode or jupyter or Spyder.  In that circumstance, when you call quickplot, the REPL terminal stays open, so the plot stays open.  

In your case, are you executing the python file directly?  Like for instance, running `python my_phidl_script.py`?  In that case, you need to turn on `blocking` because the python terminal will exit completely after it finishes running and take your plots with it.

**Comment by cloudcalvin** [comment]
Thanks
