### ISSUE TITLE
Document how _centerpoint_offset_curve is different from _parametric_offset_curve

### ISSUE THREAD

**Issue by basnijholt** [amccaugh/phidl#149]
After a lot of Git detective work, I identified that the device that I build changed after this commit: https://github.com/amccaugh/phidl/commit/1a403cc.

I am trying to assert whether the resulting (slightly different) polygons should worry me or not.

@amccaugh, would you be able to tell me how these algorithms differ, and why the new one performs better?

**Comment by amccaugh** [comment]
Good detective work, you're absolutely correct.  

`_parametric_offset_curve()` was the original implementation of the offset function used to extrude Paths.  It used `np.gradient` to generate an estimate of `dx/dt` and `dy/dt` so that we could compute the offset according to this equation [from Wikipedia](https://en.wikipedia.org/wiki/Parallel_curve#Parallel_curve_of_a_parametrically_given_curve)

<img width="286" alt="image" src="https://user-images.githubusercontent.com/2075083/173258017-db0bd2d7-1da3-4e62-8702-7a8d91a65d23.png">

The issue with was that the `np.gradient` approximation fails, very badly, when doing non-smooth curves.  So that initial release of the Path module was explicitly for smooth curves only.

However,  later by doing a little geometry, it was clear that a centerpoint-based offset (I can describe with diagrams later if desired) was almost exactly equivalent to the `np.gradient` approach for smooth curves, but with the added bonus that it could now do [sharp corners](https://phidl.readthedocs.io/en/latest/tutorials/waveguides.html#Sharp/angular-paths).

As of right now, `_centerpoint_offset_curve()` is in use and `_parametric_offset_curve()` is actually totally unused and can be deleted.  Additionally, I actually have some additional code to make a parallel-offset (for routing waveguide bundles) that never made it into the main codebase.
