### ISSUE TITLE
Migration from gdspy to gdstk

### ISSUE THREAD

**Issue by Dominik-Vogel** [amccaugh/phidl#163]
As gdspy is being sunset, are there any plans and timelines for phidl to migrate to gdstk, the successor of gdspy?
https://github.com/heitzmann/gdspy#future-of-gdspy

**Comment by amccaugh** [comment]
Hi @Dominik-Vogel , we had a brief discussion about that here if you'd like to take a look: 

* https://github.com/amccaugh/phidl/issues/140
* https://github.com/amccaugh/phidl/issues/79

**Comment by Dominik-Vogel** [comment]
Thank you @amccaugh #140 sounds very reasonable. Sorry I must have overlooked it going through the issues. Looking forward to both the development in gdstk and phidl. Thank you for all the good work so far!

**Comment by jenshnielsen** [comment]
@amccaugh Given that this has been raised 4 times or so maybe adding a note about the status to the readme ?

**Comment by jenshnielsen** [comment]
This is especially likely to come up since gdspy officially does not support python newer than 3.8

**Comment by alexsludds** [comment]
Hey folks,
I made a brief first pass at converting the phidl backend from gdspy to gdstk:
[https://github.com/alexsludds/phidl](phidl with gdstk backend)

It's not bug free, but it does generate some basic geometry. I need folks help with handling dependencies on gds/oas generation. 
In particular, if you run this example code (borrowed from the phidl examples):
[https://github.com/alexsludds/phidl/blob/master/test_phidl_gdstk_backend.py](example code)

You will see it tries to create three waveguides of different shapes. However, in the layout all waveguides have the same shape, equal to the last waveguide that was placed.

This is because of how I tried to implement the write_gds function:
[https://github.com/alexsludds/phidl/blob/c4a5abd8a485219fca940834474bcc1e66b74cee/phidl/device_layout.py#L1383](write_gds function)

I spent a few hours trying different ways to implement phidl's write_gds and have it be compatible with gdstk, but I can't get the dependency handling correct. I'm hoping this might be really obvious to someone else.

Best,
-Alex
