### ISSUE TITLE
Union of geometries

### ISSUE THREAD

**Issue by minheekwon** [amccaugh/phidl#174]
Hello!

I'm having trouble unioning geometries.

Could you please look at the code below?

```
from phidl import Device
from phidl import quickplot as qp
import phidl.geometry as pg

p = 1
a = 1
w = 2 * (p+a)
b = 5 * w       #busbar
W = 70 * w
Ng = 250

busbar = pg.rectangle(size = (((p + a) * Ng)-a, b/2), layer = 0)

SAW = Device('SAW pattern')

busbar1 = SAW.add_ref(busbar).move(origin=((w), -b/2))
busbar2 = SAW.add_ref(busbar).move(origin=((w), W))

for i in range(Ng):
    electrode_tmp = SAW << pg.rectangle(size = (p, W), layer = 0).movex(i * (p+a)).move(origin=((w), 0))
    
qp(SAW)
SAW_joined = pg.union(SAW, layer=0)
```

We need the Bragg's mirror structure for the lithography process. 

Each geometry requires one polyline from the gds file. This is because when the lines overlap, they get confused and don't recognize a completely closed shape. 

Some parts are unioned the way we want them to be, but many parts are still separate.
Is there any way to solve this?

<img width="841" alt="1" src="https://user-images.githubusercontent.com/66489512/214046201-286720a9-31f9-4130-8787-d77d7bf8316b.png">
<img width="1101" alt="2" src="https://user-images.githubusercontent.com/66489512/214046219-bcdcd732-400d-43b2-946b-dbf3f4406223.png">
<img width="1442" alt="3" src="https://user-images.githubusercontent.com/66489512/214046240-c18c9e16-4306-4ea3-9dba-e126cb2f3455.PNG">

**Comment by amccaugh** [comment]
If it's a SAW, are you trying to make this shape?

![image](https://user-images.githubusercontent.com/2075083/214116426-d09ab56c-fe84-4522-878c-3f96d4b59605.png)

because it appears what you've made is this shape:

![image](https://user-images.githubusercontent.com/2075083/214116486-f7c0aa6c-962f-4923-998d-691940ccff47.png)

If the second one is in fact what you're trying to do, it's going to have those infinitely thin "cuts" in the top because there's no such thing as "holes" in a GDS file, only closed polygons.  So this shape is not possible in GDS:

![image](https://user-images.githubusercontent.com/2075083/214116767-3c723050-12f5-49d0-a598-fe881d04d0c8.png)

but this one is:

![image](https://user-images.githubusercontent.com/2075083/214116837-9af12181-1f99-4ee5-bbfb-8c5bbcf73992.png)
